//
//  include/tanh_table_S16.h
//
//  Created by convert_model.py 
//  © 2024 JumpML
/*This file is automatically generated by gen_tanh_table.py*/
#include <stdint.h>
#include "common_def.h"

#define TANH_TABLE_SIZE_S16 65
#define TANH_TABLE_MAXINDEX_S16 64
#define TANH_DELTAX_S16 4096
#define TANH_SCALEFAC_S16 8


DSP_RWDATA_IN_DRAM DSP_ALIGN16 static const int16_t tanh_table_S16[65] = {
   0, 4075, 8025, 11743, 15143, 18173, 20813, 23066,
   24956, 26519, 27797, 28830, 29660, 30322, 30847, 31262,
   31589, 31846, 32048, 32206, 32329, 32426, 32501, 32560,
   32606, 32642, 32670, 32691, 32708, 32721, 32732, 32740,
   32746, 32751, 32755, 32758, 32760, 32762, 32763, 32764,
   32765, 32766, 32766, 32767, 32767, 32767, 32767, 32767,
   32767, 32767, 32767, 32767, 32767, 32767, 32767, 32767,
   32767, 32767, 32767, 32767, 32767, 32767, 32767, 32767,
   32767
};

