//
//  include/tanh_table.h
//
//  Created by convert_model.py 
//  © 2024 JumpML
/*This file is automatically generated by gen_tanh_table.py*/
#include <stdint.h>
#include "common_def.h"

#define TANH_TABLE_SIZE 65
#define TANH_TABLE_MAXINDEX 64
#define TANH_DELTAX 0.125f
#define TANH_SCALEFAC 8


DSP_RWDATA_IN_DRAM DSP_ALIGN16 static const float tanh_table[65] = {
   0.0f, 0.124353f, 0.244919f, 0.358357f, 0.462117f, 0.5546f, 0.635149f, 0.703906f,
   0.761594f, 0.809301f, 0.848284f, 0.879827f, 0.905148f, 0.925346f, 0.941376f, 0.954045f,
   0.964028f, 0.971873f, 0.978026f, 0.982845f, 0.986614f, 0.98956f, 0.99186f, 0.993655f,
   0.995055f, 0.996147f, 0.996998f, 0.997661f, 0.998178f, 0.998581f, 0.998894f, 0.999139f,
   0.999329f, 0.999478f, 0.999593f, 0.999683f, 0.999753f, 0.999808f, 0.99985f, 0.999883f,
   0.999909f, 0.999929f, 0.999945f, 0.999957f, 0.999967f, 0.999974f, 0.99998f, 0.999984f,
   0.999988f, 0.99999f, 0.999993f, 0.999994f, 0.999995f, 0.999996f, 0.999997f, 0.999998f,
   0.999998f, 0.999999f, 0.999999f, 0.999999f, 0.999999f, 1.0f, 1.0f, 1.0f,
   1.0f,
};

